apiVersion: v1
kind: Service
metadata:
  name: spam-detection-service
spec:
  selector:
    app: spam-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Port where Django app is running inside container
  type: LoadBalancer  # Exposes the service to the internet (or use ClusterIP for internal access only)
 
